INSERT INTO tb_category(name) VALUES('Action');
INSERT INTO tb_category(name) VALUES('Comedy');
INSERT INTO tb_category(name) VALUES('Drama');
INSERT INTO tb_category(name) VALUES('Horror');
INSERT INTO tb_category(name) VALUES('Sci-fi');

INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Fast and Furious', 'Rob Cohen', 2001, 1);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Avengers', 'Anthony Russo, Joe Russo, Joss Whedon', 2012, 1);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Back to the future', 'Robert Zemeckis', 1985, 2);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('The Simpsons Movie', 'David Silverman', 2007, 2);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Forrest Gump', 'Robert Zemeckis', 1994, 3);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Schindlers List', 'Steven Spielberg', 1993, 3);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('It', 'Andy Muschietti', 2017, 4);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('The Conjuring', 'Michael Chaves, James Wan', 2013, 4);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('The Conjuring 2', 'James Wan', 2016, 4);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Annabelle', 'John R. Leonetti', 2014, 4);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Star Wars', 'George Lucas', 1977, 5);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Matrix', 'Lana Wachowski, Lilly Wachowski', 1999, 5);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('The Hunger Games', 'Francis Lawrence, Gary Ross', 2012, 5);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('The Hunger Games: Catching Fire', 'Francis Lawrence', 2013, 5);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('The Hunger Games: Mockingjay - Part 1', 'Francis Lawrence', 2014, 5);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('The Hunger Games: Mockingjay - Part 2', 'Francis Lawrence', 2015, 5);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Kick ass', 'Matthew Vaughn, Jeff Wadlow', 2010, 1);
INSERT INTO tb_movie(name, director, release_year, category_id) VALUES('Kick ass 2', 'Jeff Wadlow', 2013, 1);